/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as TodayRouteImport } from './routes/today'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppCatalogRouteImport } from './routes/_app/catalog'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppFrontdeskRouteImport } from './routes/_app/frontdesk'
import { Route as AppHighlevelRouteImport } from './routes/_app/highlevel'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppWebsiteRouteImport } from './routes/_app/website'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BookSlugRouteImport } from './routes/book/$slug'
import { Route as KioskSlugRouteImport } from './routes/kiosk/$slug'
import { Route as ManageSlugTokenRouteImport } from './routes/manage/$slug/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppFrontdeskRoute = AppFrontdeskRouteImport.update({
  id: '/frontdesk',
  path: '/frontdesk',
  getParentRoute: () => AppRoute,
} as any)
const AppHighlevelRoute = AppHighlevelRouteImport.update({
  id: '/highlevel',
  path: '/highlevel',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteRoute = AppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskSlugRoute = KioskSlugRouteImport.update({
  id: '/kiosk/$slug',
  path: '/kiosk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSlugTokenRoute = ManageSlugTokenRouteImport.update({
  id: '/manage/$slug/$token',
  path: '/manage/$slug/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/calendar': typeof AppCalendarRoute
  '/catalog': typeof AppCatalogRoute
  '/clients': typeof AppClientsRoute
  '/frontdesk': typeof AppFrontdeskRoute
  '/highlevel': typeof AppHighlevelRoute
  '/insights': typeof AppInsightsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/website': typeof AppWebsiteRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$slug': typeof BookSlugRoute
  '/kiosk/$slug': typeof KioskSlugRoute
  '/manage/$slug/$token': typeof ManageSlugTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/calendar': typeof AppCalendarRoute
  '/catalog': typeof AppCatalogRoute
  '/clients': typeof AppClientsRoute
  '/frontdesk': typeof AppFrontdeskRoute
  '/highlevel': typeof AppHighlevelRoute
  '/insights': typeof AppInsightsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/website': typeof AppWebsiteRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$slug': typeof BookSlugRoute
  '/kiosk/$slug': typeof KioskSlugRoute
  '/manage/$slug/$token': typeof ManageSlugTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/today': typeof TodayRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/frontdesk': typeof AppFrontdeskRoute
  '/_app/highlevel': typeof AppHighlevelRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/website': typeof AppWebsiteRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$slug': typeof BookSlugRoute
  '/kiosk/$slug': typeof KioskSlugRoute
  '/manage/$slug/$token': typeof ManageSlugTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/today'
    | '/calendar'
    | '/catalog'
    | '/clients'
    | '/frontdesk'
    | '/highlevel'
    | '/insights'
    | '/sales'
    | '/settings'
    | '/team'
    | '/website'
    | '/api/$'
    | '/book/$slug'
    | '/kiosk/$slug'
    | '/manage/$slug/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/today'
    | '/calendar'
    | '/catalog'
    | '/clients'
    | '/frontdesk'
    | '/highlevel'
    | '/insights'
    | '/sales'
    | '/settings'
    | '/team'
    | '/website'
    | '/api/$'
    | '/book/$slug'
    | '/kiosk/$slug'
    | '/manage/$slug/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/today'
    | '/_app/calendar'
    | '/_app/catalog'
    | '/_app/clients'
    | '/_app/frontdesk'
    | '/_app/highlevel'
    | '/_app/insights'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/website'
    | '/api/$'
    | '/book/$slug'
    | '/kiosk/$slug'
    | '/manage/$slug/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  TodayRoute: typeof TodayRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BookSlugRoute: typeof BookSlugRoute
  KioskSlugRoute: typeof KioskSlugRoute
  ManageSlugTokenRoute: typeof ManageSlugTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frontdesk': {
      id: '/_app/frontdesk'
      path: '/frontdesk'
      fullPath: '/frontdesk'
      preLoaderRoute: typeof AppFrontdeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/highlevel': {
      id: '/_app/highlevel'
      path: '/highlevel'
      fullPath: '/highlevel'
      preLoaderRoute: typeof AppHighlevelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website': {
      id: '/_app/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AppWebsiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/$slug': {
      id: '/kiosk/$slug'
      path: '/kiosk/$slug'
      fullPath: '/kiosk/$slug'
      preLoaderRoute: typeof KioskSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$slug/$token': {
      id: '/manage/$slug/$token'
      path: '/manage/$slug/$token'
      fullPath: '/manage/$slug/$token'
      preLoaderRoute: typeof ManageSlugTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppClientsRoute: typeof AppClientsRoute
  AppFrontdeskRoute: typeof AppFrontdeskRoute
  AppHighlevelRoute: typeof AppHighlevelRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWebsiteRoute: typeof AppWebsiteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppClientsRoute: AppClientsRoute,
  AppFrontdeskRoute: AppFrontdeskRoute,
  AppHighlevelRoute: AppHighlevelRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWebsiteRoute: AppWebsiteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  TodayRoute: TodayRoute,
  ApiSplatRoute: ApiSplatRoute,
  BookSlugRoute: BookSlugRoute,
  KioskSlugRoute: KioskSlugRoute,
  ManageSlugTokenRoute: ManageSlugTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
